#!/bin/bash
kubectl create secret generic aws-cred \
--from-literal=key-id='AKIARUS******' \
--from-literal=access-key='9stBy1nPndu********' \
--from-literal=account='11290*****' \
--from-literal=region='us-west-1' \
--from-literal=default-region='us-west-1'
